# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.0"
slug: example
description: Example add-on
url: "https://github.com/ottes/hassio-addons/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: before
ports:
  8888/tcp: 8888  
